name: "PR Changelog Generator"
description: "A GitHub Action to generate a Changelog from schul-cloud/pr-changelog-sender mongodb entries"
branding:
  icon: "edit"
  color: "gray-dark"
inputs:
  token:
    description: "Token is required to get the list of associated PRs for the current release"
    required: true
  mongo-uri:
    description: "mongodb+srv://<username>:<password>@<your-cluster-url>/test?retryWrites=true&w=majority"
    required: true
  mongo-db:
    description: "mongo database name"
    default: "pr-changelog"
  mongo-collection:
    description: "mongo collection name"
    default: "pr-changes"
  changelog-sections:
    description: "sections to include in the changelog"
    default: '["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]'
outputs:
  release_tag:
    description: "The tag of the current release"
  pull_requests:
    description: "A JSON.stringified list of all PRs that are in the current release"
  changelog:
    description: "The Markdown Formatted Changelog"
runs:
  using: "node12"
  main: "dist/index.js"
