name: Release
on:
  pull_request:
    types: [closed]

jobs:
  send-changelog:
    runs-on: ubuntu-latest
    name: "Upload Changelog"
    steps:
      - name: Upload PR Changelog
        uses: schul-cloud/PR-Changelog-Sender@master
        with:
          mongo-uri: ${{ secrets.MONGO_URI }}
          mongo-db: "pr-changelog"
          mongo-collection: "pr-changes"
          changelog-sections: '["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security", "Uncategorized"]'
