name: Release
on:
  release:
    types: [published]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    name: Generate Changelog
    steps:
      - name: generate changelog
        uses: schul-cloud/PR-Changelog-Generator@master
        id: changelog
        with:
          token: ${{ secrets.SC_BOT_GITHUB_TOKEN }}
          changelog-sections: '["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security", "Uncategorized"]'
        env:
          ACTIONS_STEP_DEBUG: true
      - name: clone repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SC_BOT_GITHUB_TOKEN }}
          ref: "master"
      - name: save changelog
        runs: echo -e '${{ steps.changelog.outputs.changelog }}' > "CHANGELOG/${{ steps.changelog.outputs.release_tag }}.md"
      - name: commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "add changelog ${{ steps.changelog.outputs.release_tag }}"
