name: Test

on:
  push:
    branch:
      - master
  release:
    types: [published, created, edited]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    name: Generate Changelog
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "master"
      - name: generate changelog
        uses: ./
        with:
          gh-token: ${{ secrets.SC_BOT_GITHUB_TOKEN }}
          mongo-uri: ${{ secrets.MONGO_URI }}
          mongo-db: "pr-changelog"
          mongo-collection: "pr-changes"
          changelog-sections: '["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security", "Uncategorized"]'
