name: Test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm ci
        run: npm ci --prefer-offline --no-audit
      - name: npm run test
        run: npm run test
